"""gplug_smi – gPlug smart-meter interface for ESPHome.

Embeds the SPA (gzipped) and the preset list, wires UART + web server, and
exposes /api/* endpoints. Meter-specific behaviour is runtime data (descriptor).
"""
import gzip
import json
from pathlib import Path

import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import esp32, socket, uart, web_server_base
from esphome.components.web_server_base import CONF_WEB_SERVER_BASE_ID
from esphome.const import CONF_ID
from esphome.core import CORE

# ota.web_server: the POST /update handler the SPA's firmware card uploads to. The captive portal
# fork auto-loads it too, but the card must not depend on that.
AUTO_LOAD = ["web_server_base", "json", "ota.web_server", "socket"]
DEPENDENCIES = ["uart", "wifi", "esp32", "captive_portal"]
CODEOWNERS = ["@gplug"]

CONF_SPA = "spa"
CONF_PRESETS = "presets"
CONF_SPA_RAW_ID = "spa_raw_id"
CONF_PRESETS_RAW_ID = "presets_raw_id"
CONF_MANIFEST_RAW_ID = "manifest_raw_id"
CONF_ICON_RAW_ID = "icon_raw_id"
CONF_OTA_PASSWORD = "ota_password"
CONF_UPDATE_ID = "update_id"
# Referenced by the sensor/text_sensor platforms to find the component.
CONF_GPLUG_SMI_ID = "gplug_smi_id"
OTA_USERNAME = "admin"

UpdateEntity = cg.esphome_ns.namespace("update").class_("UpdateEntity")
gplug_ns = cg.esphome_ns.namespace("gplug_smi")
GplugSmi = gplug_ns.class_("GplugSmi", cg.Component, uart.UARTDevice)


# Bundled assets, committed next to this file so the component is self-contained when pulled in
# as a git external component (dashboard adoption / `packages:` import): a remote package can't
# reference files relative to the user's config dir. Regenerated by `npm run build` /
# `npm run presets` in ../../../spa.
BUNDLED_SPA = Path(__file__).parent / "spa.html.gz"
BUNDLED_PRESETS = Path(__file__).parent / "presets.json"
# Home-screen shortcut (manifest + icon), also written by `npm run build`; not user-overridable.
BUNDLED_MANIFEST = Path(__file__).parent / "manifest.webmanifest"
BUNDLED_ICON = Path(__file__).parent / "icon.png"


def _file(value):
    value = cv.string(value)
    path = Path(CORE.relative_config_path(value))
    if not path.is_file():
        raise cv.Invalid(f"File not found: {path}")
    return str(path)


def _bundled(path: Path):
    def validator(value):
        if value is None:
            if not path.is_file():
                raise cv.Invalid(f"Bundled file missing: {path} (run the SPA build)")
            return str(path)
        return _file(value)
    return validator


# lwIP's socket pool (CONFIG_LWIP_MAX_SOCKETS) is one table shared by every listener, UDP socket,
# API client, the MQTT client and every HTTP session. ESPHome sizes it from what components
# register, and without this it came out at 12: 3 listeners + 3 UDP + api 3 + captive_portal 3.
# That is below what the image can actually hold open -- api `max_connections` 5, the esp-mqtt
# socket (not an ESPHome `mqtt:` component, so ESPHome does not count it) and esp httpd's
# `max_open_sockets` 7 -- so the pool filled before httpd's own LRU purge (which only runs once
# httpd itself holds 7) could ever free anything. A browser that left Wi-Fi mid-session holds its
# keep-alive socket forever (httpd has no idle timeout and TCP keepalive is off), and after a few
# of those accept() failed with ENFILE on port 80, 6053 and 3232 alike: the device answered ping
# but closed every connection right after the handshake, until power-cycled (gPlugK 2026-09-26).
# The 7 registered here make the pool 19, i.e. large enough for everything at once, so httpd's
# purge is what bounds HTTP sessions again. Cost is static RAM only (firmware/MEMORY.md).
_SOCKETS_BEYOND_ESPHOME_COUNT = 7   # mqtt 1 + api (5 - 3) + httpd (7 - 3)

CONFIG_SCHEMA = cv.All(
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(GplugSmi),
            cv.GenerateID(CONF_WEB_SERVER_BASE_ID): cv.use_id(web_server_base.WebServerBase),
            cv.GenerateID(CONF_SPA_RAW_ID): cv.declare_id(cg.uint8),
            cv.GenerateID(CONF_PRESETS_RAW_ID): cv.declare_id(cg.uint8),
            cv.GenerateID(CONF_MANIFEST_RAW_ID): cv.declare_id(cg.uint8),
            cv.GenerateID(CONF_ICON_RAW_ID): cv.declare_id(cg.uint8),
            cv.Optional(CONF_SPA, default=None): _bundled(BUNDLED_SPA),
            cv.Optional(CONF_PRESETS, default=None): _bundled(BUNDLED_PRESETS),
            # Optional: protects the browser upload (`POST /update`, ota.web_server, used by the
            # SPA's firmware card) with HTTP Basic auth, user "admin". Empty = no auth. gplug.yaml feeds
            # the same value to `ota: password:` so both OTA paths share one password.
            cv.Optional(CONF_OTA_PASSWORD, default=""): cv.sensitive(),
            # Optional: the `update: platform: http_request` entity behind the firmware card's
            # "Check for updates" / install from the release (GET/POST /api/update*). Without it
            # those routes answer 404 / state "unavailable" and the card offers the file upload only.
            cv.Optional(CONF_UPDATE_ID): cv.use_id(UpdateEntity),
        }
    )
    .extend(cv.COMPONENT_SCHEMA)
    .extend(uart.UART_DEVICE_SCHEMA),
    socket.consume_sockets(_SOCKETS_BEYOND_ESPHOME_COUNT, "gplug_smi"),
)


def _gz_bytes(path: str) -> bytes:
    data = Path(path).read_bytes()
    if path.endswith(".gz"):
        return data
    return gzip.compress(data, compresslevel=9, mtime=0)


async def to_code(config):
    if CORE.is_esp32:
        # Ensures ESP-IDF links mbedtls (needed for mbedtls_gcm_* AES-128-GCM decrypt in
        # aes_gcm.h). Without this, this component's flat "src" pseudo-component gets no
        # REQUIRES on at least the platformio-espressif32 (pioarduino) build ESPHome uses
        # here, and mbedtls_gcm_* comes back undefined at link time despite ESP-IDF already
        # building libmbedcrypto.a for WiFi/TLS elsewhere. See CMakeLists.txt.in for detail.
        esp32.add_extra_build_file("src/CMakeLists.txt", Path(__file__).parent / "CMakeLists.txt.in")
        # esp-mqtt for MQTT publishing (mqtt.cpp). ESPHome excludes the IDF component by default and
        # only re-includes it for its own `mqtt:`, whose compile-time broker and fixed topic scheme
        # do not fit runtime templates (DECISIONS.md 2026-09-26).
        esp32.include_builtin_idf_component("mqtt")
        # esp-mqtt sends one queued message per pass of its task and then waits up to
        # MQTT_POLL_READ_TIMEOUT_MS for incoming data. At QoS 0 nothing comes back, so with the
        # 1000 ms default "one message per value" drained ~1 message/s and overflowed the outbox
        # (found in review, 2026-09-26); 50 ms allows ~20/s. Only plain TCP is used, so the TLS and
        # WebSocket transports are left out.
        esp32.add_idf_sdkconfig_option("CONFIG_MQTT_USE_CUSTOM_CONFIG", True)
        esp32.add_idf_sdkconfig_option("CONFIG_MQTT_POLL_READ_TIMEOUT_MS", 50)
        esp32.add_idf_sdkconfig_option("CONFIG_MQTT_TRANSPORT_SSL", False)
        esp32.add_idf_sdkconfig_option("CONFIG_MQTT_TRANSPORT_WEBSOCKET", False)
        # TCP control blocks: the IDF default of 16 is now below the 19-socket pool above, and
        # closed HTTP sessions sit in TIME_WAIT for 2 x CONFIG_LWIP_TCP_MSL on top of the open
        # ones. lwIP does evict the oldest TIME_WAIT block when it runs out, but an empty pool
        # drops SYNs; 20 leaves room for the pool plus a few TIME_WAITs.
        esp32.add_idf_sdkconfig_option("CONFIG_LWIP_MAX_ACTIVE_TCP", 20)

    base = await cg.get_variable(config[CONF_WEB_SERVER_BASE_ID])
    var = cg.new_Pvariable(config[CONF_ID], base)
    await cg.register_component(var, config)
    await uart.register_uart_device(var, config)

    spa = _gz_bytes(config[CONF_SPA])
    spa_arr = cg.static_const_array(config[CONF_SPA_RAW_ID], cg.ArrayInitializer(*spa))
    cg.add(var.set_spa(spa_arr, len(spa)))

    presets = json.loads(Path(config[CONF_PRESETS]).read_text(encoding="utf-8"))
    minified = json.dumps(presets, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    presets_gz = gzip.compress(minified, compresslevel=9, mtime=0)
    presets_arr = cg.static_const_array(config[CONF_PRESETS_RAW_ID], cg.ArrayInitializer(*presets_gz))
    cg.add(var.set_presets(presets_arr, len(presets_gz)))

    manifest = _gz_bytes(str(BUNDLED_MANIFEST))
    manifest_arr = cg.static_const_array(config[CONF_MANIFEST_RAW_ID], cg.ArrayInitializer(*manifest))
    icon = BUNDLED_ICON.read_bytes()   # PNG is already deflated; gzip would not shrink it
    icon_arr = cg.static_const_array(config[CONF_ICON_RAW_ID], cg.ArrayInitializer(*icon))
    cg.add(var.set_home_screen(manifest_arr, len(manifest), icon_arr, len(icon)))

    # web_server_base wraps every handler registered via add_handler() -- only ota.web_server's
    # /update here; the SPA and captive portal use add_handler_without_auth() -- in Basic auth once
    # a username is set. Set before setup(), since the wrap happens when the handler is added.
    if CONF_UPDATE_ID in config:
        cg.add(var.set_update(await cg.get_variable(config[CONF_UPDATE_ID])))

    if config[CONF_OTA_PASSWORD]:
        cg.add(var.set_ota_auth(True))
        # POST /api/update/install checks it itself: that route is registered without auth.
        cg.add(var.set_ota_password(config[CONF_OTA_PASSWORD]))
        cg.add_define("USE_WEBSERVER_AUTH")
        cg.add(base.set_auth_username(OTA_USERNAME))
        cg.add(base.set_auth_password(config[CONF_OTA_PASSWORD]))
