"""gplug_smi – gPlug smart-meter interface for ESPHome.

Embeds the SPA (gzipped) and the preset list, wires UART + web server, and
exposes /api/* endpoints. Meter-specific behaviour is runtime data (descriptor).
"""
import gzip
import json
from pathlib import Path

import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import esp32, uart, web_server_base
from esphome.components.web_server_base import CONF_WEB_SERVER_BASE_ID
from esphome.const import CONF_ID
from esphome.core import CORE

AUTO_LOAD = ["web_server_base", "json"]
DEPENDENCIES = ["uart", "wifi", "esp32", "captive_portal"]
CODEOWNERS = ["@gplug"]

CONF_SPA = "spa"
CONF_PRESETS = "presets"
CONF_SPA_RAW_ID = "spa_raw_id"
CONF_PRESETS_RAW_ID = "presets_raw_id"
CONF_OTA_PASSWORD = "ota_password"
OTA_USERNAME = "admin"

gplug_ns = cg.esphome_ns.namespace("gplug_smi")
GplugSmi = gplug_ns.class_("GplugSmi", cg.Component, uart.UARTDevice)


# Bundled assets, committed next to this file so the component is self-contained when pulled in
# as a git external component (dashboard adoption / `packages:` import): a remote package can't
# reference files relative to the user's config dir. Regenerated by `npm run build` /
# `npm run presets` in ../../../spa.
BUNDLED_SPA = Path(__file__).parent / "spa.html.gz"
BUNDLED_PRESETS = Path(__file__).parent / "presets.json"


def _file(value):
    value = cv.string(value)
    path = Path(CORE.relative_config_path(value))
    if not path.is_file():
        raise cv.Invalid(f"File not found: {path}")
    return str(path)


def _bundled(path: Path):
    def validator(value):
        if value is None:
            if not path.is_file():
                raise cv.Invalid(f"Bundled file missing: {path} (run the SPA build)")
            return str(path)
        return _file(value)
    return validator


CONFIG_SCHEMA = (
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(GplugSmi),
            cv.GenerateID(CONF_WEB_SERVER_BASE_ID): cv.use_id(web_server_base.WebServerBase),
            cv.GenerateID(CONF_SPA_RAW_ID): cv.declare_id(cg.uint8),
            cv.GenerateID(CONF_PRESETS_RAW_ID): cv.declare_id(cg.uint8),
            cv.Optional(CONF_SPA, default=None): _bundled(BUNDLED_SPA),
            cv.Optional(CONF_PRESETS, default=None): _bundled(BUNDLED_PRESETS),
            # Optional: protects the browser OTA form (`/update`, from the captive portal's
            # ota.web_server) with HTTP Basic auth, user "admin". Empty = no auth. gplug.yaml feeds
            # the same value to `ota: password:` so both OTA paths share one password.
            cv.Optional(CONF_OTA_PASSWORD, default=""): cv.sensitive(),
        }
    )
    .extend(cv.COMPONENT_SCHEMA)
    .extend(uart.UART_DEVICE_SCHEMA)
)


def _gz_bytes(path: str) -> bytes:
    data = Path(path).read_bytes()
    if path.endswith(".gz"):
        return data
    return gzip.compress(data, compresslevel=9, mtime=0)


async def to_code(config):
    if CORE.is_esp32:
        # Ensures ESP-IDF links mbedtls (needed for mbedtls_gcm_* AES-128-GCM decrypt in
        # aes_gcm.h). Without this, this component's flat "src" pseudo-component gets no
        # REQUIRES on at least the platformio-espressif32 (pioarduino) build ESPHome uses
        # here, and mbedtls_gcm_* comes back undefined at link time despite ESP-IDF already
        # building libmbedcrypto.a for WiFi/TLS elsewhere. See CMakeLists.txt.in for detail.
        esp32.add_extra_build_file("src/CMakeLists.txt", Path(__file__).parent / "CMakeLists.txt.in")

    base = await cg.get_variable(config[CONF_WEB_SERVER_BASE_ID])
    var = cg.new_Pvariable(config[CONF_ID], base)
    await cg.register_component(var, config)
    await uart.register_uart_device(var, config)

    spa = _gz_bytes(config[CONF_SPA])
    spa_arr = cg.static_const_array(config[CONF_SPA_RAW_ID], cg.ArrayInitializer(*spa))
    cg.add(var.set_spa(spa_arr, len(spa)))

    presets = json.loads(Path(config[CONF_PRESETS]).read_text(encoding="utf-8"))
    minified = json.dumps(presets, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    presets_gz = gzip.compress(minified, compresslevel=9, mtime=0)
    presets_arr = cg.static_const_array(config[CONF_PRESETS_RAW_ID], cg.ArrayInitializer(*presets_gz))
    cg.add(var.set_presets(presets_arr, len(presets_gz)))

    # web_server_base wraps every handler registered via add_handler() -- only ota.web_server's
    # /update here; the SPA and captive portal use add_handler_without_auth() -- in Basic auth once
    # a username is set. Set before setup(), since the wrap happens when the handler is added.
    if config[CONF_OTA_PASSWORD]:
        cg.add_define("USE_WEBSERVER_AUTH")
        cg.add(base.set_auth_username(OTA_USERNAME))
        cg.add(base.set_auth_password(config[CONF_OTA_PASSWORD]))
