// UI strings, German first (matches the existing gPlug UI). Swap this module for other languages.
export const S = {
  brand: "IoT-Adapter",
  title: "gPlug Einrichtung",
  next: "Weiter",
  back: "Zurück",
  skip: "Überspringen",
  finish: "Fertig",
  loading: "Lade…",
  error: "Fehler",
  retry: "Erneut versuchen",
  errTimeout: "Gerät antwortet nicht. Bitte prüfen, ob es eingeschaltet und erreichbar ist, und erneut versuchen.",
  errNetwork: "Gerät nicht erreichbar. WLAN-Verbindung zum gPlug prüfen.",
  errServer: "Fehler vom Gerät",

  welcome: "Willkommen",
  welcomeText: "Dieser Assistent richtet Ihren gPlug in vier Schritten ein: Gerät, Smart Meter, WLAN, Abschluss.",
  version: "Firmware",

  hardware: "Gerät",
  hardwareText: "Welchen gPlug haben Sie? Die Bezeichnung steht auf dem Gehäuse.",
  pins: "Pin-Belegung (nur bei Bedarf ändern)",
  pinRx: "HAN RX",
  pinRed: "LED rot",
  pinGreen: "LED grün",
  pinBlue: "LED blau",
  pinButton: "Taste",
  none: "–",

  meter: "Smart Meter",
  meterText: "Wählen Sie das Profil Ihres Netzbetreibers. Es bestimmt Protokoll, Baudrate und die gelesenen Werte.",
  key: "Schlüssel (GUEK)",
  keyHint: "32 Hex-Zeichen. Sie erhalten den Schlüssel von Ihrem Netzbetreiber. Er wird nur auf dem Gerät gespeichert und nie wieder angezeigt.",
  keyInvalid: "Schlüssel muss aus 32 Hex-Zeichen bestehen.",
  encrypted: "verschlüsselt",
  noPresetForVariant: "Für dieses Gerät ist kein Profil hinterlegt.",
  showAll: "Alle Profile anzeigen",
  values: "Werte",

  wifi: "WLAN",
  wifiText: "Verbinden Sie den gPlug mit Ihrem Heimnetz. Danach ist er unter der unten angezeigten Adresse erreichbar.",
  ssid: "Netzwerk",
  password: "Passwort",
  scan: "Netzwerke suchen",
  manual: "Netzwerk manuell eingeben",
  connecting: "Verbinde…",
  connected: "Verbunden",
  connectFailed: "Verbindung fehlgeschlagen. Passwort prüfen.",

  done: "Abschluss",
  doneText: "Der gPlug ist eingerichtet.",
  reachable: "Erreichbar unter",
  meterData: "Smart Meter",
  waitingData: "Warte auf Daten vom Zähler…",
  dataOk: "Daten aktuell",
  dataStale: "Keine Daten",
  keyWrong: "Schlüssel ungültig",
  openLive: "Live-Ansicht öffnen",
  bezug: "Bezug",
  einspeisung: "Einspeisung",
};
