// UI strings, German first (matches the existing gPlug UI). Swap this module for other languages.
export const S = {
  brand: "IoT-Adapter",
  title: "gPlug Einrichtung",
  next: "Weiter",
  back: "Zurück",
  skip: "Überspringen",
  finish: "Fertig",
  loading: "Lade…",
  error: "Fehler",
  retry: "Erneut versuchen",
  errTimeout: "Gerät antwortet nicht. Bitte prüfen, ob es eingeschaltet und erreichbar ist, und erneut versuchen.",
  errNetwork: "Gerät nicht erreichbar. WLAN-Verbindung zum gPlug prüfen.",
  errServer: "Fehler vom Gerät",

  welcome: "Willkommen",
  welcomeText: "Dieser Assistent richtet Ihren gPlug in vier Schritten ein: Gerät, Smart Meter, WLAN, Abschluss.",
  version: "Firmware",

  hardware: "Gerät",
  hardwareText: "Welchen gPlug haben Sie? Die Bezeichnung steht auf dem Gehäuse.",
  pins: "Pin-Belegung (nur bei Bedarf ändern)",
  pinRx: "HAN RX",
  pinRed: "LED rot",
  pinGreen: "LED grün",
  pinBlue: "LED blau",
  pinButton: "Taste",
  none: "–",

  meter: "Smart Meter",
  meterText: "Wählen Sie das Profil Ihres Netzbetreibers. Es bestimmt Protokoll, Baudrate und die gelesenen Werte.",
  key: "Schlüssel (GUEK)",
  keyHint: "32 Hex-Zeichen. Sie erhalten den Schlüssel von Ihrem Netzbetreiber. Er wird nur auf dem Gerät gespeichert und nie wieder angezeigt.",
  keyInvalid: "Schlüssel muss aus 32 Hex-Zeichen bestehen.",
  encrypted: "verschlüsselt",
  noPresetForVariant: "Für dieses Gerät ist kein Profil hinterlegt.",
  showAll: "Alle Profile anzeigen",
  values: "Werte",

  wifi: "WLAN",
  wifiText: "Verbinden Sie den gPlug mit Ihrem Heimnetz. Danach ist er unter der unten angezeigten Adresse erreichbar.",
  ssid: "Netzwerk",
  password: "Passwort",
  scan: "Netzwerke suchen",
  manual: "Netzwerk manuell eingeben",
  connecting: "Verbinde…",
  connected: "Verbunden",
  connectFailed: "Verbindung fehlgeschlagen. Passwort prüfen.",
  changeWifi: "WLAN ändern",

  done: "Abschluss",
  doneText: "Der gPlug ist eingerichtet.",
  waitingData: "Warte auf Daten vom Zähler…",
  dataOk: "Daten aktuell",
  noData: "Keine Daten",
  noDataHint: "Der Zähler sendet nichts. Anschluss, Profil und Schlüssel prüfen.",
  keyWrongHint: "Der Zähler sendet verschlüsselt, aber der Schlüssel (GUEK) passt nicht.",
  keyWrong: "Schlüssel ungültig",
  openLive: "Live-Ansicht öffnen",


  // live screen chrome
  tabLive: "Live",
  tabHist: "Verlauf",
  tabStream: "Strom",
  tabSetup: "Setup",
  screenLive: "Live",
  screenHist: "Verlauf",
  screenStream: "Datenstrom",
  screenSetup: "Gerät",
  wlan: "WLAN",
  offline: "offline",

  // Live
  activePower: "Wirkleistung 1.7.0 / 2.7.0",
  drawFromGrid: "Bezug aus dem Netz",
  feedToGrid: "Einspeisung ins Netz",
  ago60: "−60 min",
  now: "jetzt",
  max: "max",
  importLbl: "Bezug 1.8.0",
  exportLbl: "Einspeisung 2.8.0",
  phases: "Phasen · 21/41/61.7.0",

  // Verlauf
  range10: "10 Min",
  range60: "60 Min",
  netPower: "Netto-Leistung",
  samples: (n) => `${n} Samples`,
  ago10: "−10 min",
  statMin: "Min",
  statMax: "Max",
  statAvg: "Mittel",
  registers: "Register im Ringpuffer",

  // Datenstrom
  streamRaw: "Roh · verschlüsselt",
  streamPlain: "Entschlüsselt",
  tailOn: "Live-Mitschnitt läuft",
  tailOff: "Ansicht eingefroren",
  tailOnNote: (n, kb) => `Ringpuffer ${n} Frames · ~${kb} kB · älteste Frames fallen raus`,
  tailOffNote: "Anzeige aktualisiert sich nicht, das Gerät zeichnet weiter auf",
  streamSelectAll: "Alle auswählen",
  streamDeselectAll: "Auswahl aufheben",
  selCount: (n, total) => `${n} von ${total} Frames ausgewählt`,
  selNone: "Ohne Auswahl wird der ganze Puffer exportiert",
  frameMetaRaw: "GCM ciphertext",
  frameMetaPlain: "Klartext",
  crcOk: "CRC OK",
  crcFail: "CRC FAIL",
  frameTxt: "Frame als .txt",
  copy: "Kopieren",
  copied: "Kopiert",
  exportSel: "Auswahl exportieren",
  exportAll: "Puffer exportieren",
  exportNoteSel: (n) => `${n} ausgewählte Frames als Hex-Text, ein Frame pro Block, mit Zeitstempel und CRC.`,
  exportNoteAll: (n) => `Alle ${n} gepufferten Frames als Hex-Text, ein Frame pro Block, mit Zeitstempel und CRC.`,
  dlRaw: "Roh-Hex .txt",
  dlPlain: "Entschlüsselt .txt",
  dlHint: "Schlüssel wird nie mitexportiert.",
  streamEmptyDsmr: "Dieses Profil überträgt unverschlüsselte Klartext-Telegramme (DSMR) — keine rohen DLMS-Frames vorhanden.",
  streamEmptyWaiting: "Noch keine Frames empfangen.",

  // Setup tab
  setupConn: "Verbindung",
  host: "Host",
  ip: "IP",
  profile: "Profil",
  firmware: "Firmware",
  setupKey: "Schlüssel (GUEK)",
  keySet: "gültig",
  keyInvalidBadge: "ungültig",
  keyNote: "Nur auf dem Gerät gespeichert. Wird nie im Klartext angezeigt oder exportiert.",
  dimMode: "Nachtmodus",
  dimModeHint: "Abgedunkelt für Schutzraum und Nachtdienst",
};
